import { useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, FileAudio, HelpCircle, Image, Mic2, Music2, Pause, Play, Sparkles, Upload, Video, Volume2, X } from 'lucide-react';
import { useVideoKaraokeProject } from './video-karaoke/useVideoKaraokeProject';

const steps = ['Canción', 'Letra', 'Karaoke', 'Diseño', 'Exportar'];

export function VideoKaraokePreview({ credits = 1248 }: { credits?: number }) {
  const { step, setStep, format, setFormat, preset, setPreset } = useVideoKaraokeProject();
  const [fileName, setFileName] = useState('Si te vuelves a enamorar.mp3');
  const [hasAudio, setHasAudio] = useState(false);
  const [playing, setPlaying] = useState(false);
  const [lyricsMode, setLyricsMode] = useState('auto');
  const [removeVoice, setRemoveVoice] = useState(true);
  const [showNotice, setShowNotice] = useState(false);
  const [showResult, setShowResult] = useState(false);
  const [fontSize, setFontSize] = useState(30);
  const [textColor, setTextColor] = useState('#ffffff');
  const [activeColor, setActiveColor] = useState('#ff2f92');
  const [instrumentalVolume, setInstrumentalVolume] = useState(100);
  const [chorusVolume, setChorusVolume] = useState(60);
  const [pitch, setPitch] = useState(0);
  const [speed, setSpeed] = useState(1);
  const [fontFamily, setFontFamily] = useState('Montserrat');
  const [position, setPosition] = useState('Centro inferior');
  const [alignment, setAlignment] = useState('Centrada');
  const fileRef = useRef<HTMLInputElement>(null);
  const selectFile = (file?: File) => { if (file) { setFileName(file.name); setHasAudio(true); } };

  if (showResult) return <KaraokeResult onAgain={()=>{setShowResult(false);setStep(1)}} />;
  return <div className="h-full overflow-y-auto bg-[#050611] text-white">
    <input ref={fileRef} type="file" accept="audio/*,video/mp4" className="hidden" onChange={e => selectFile(e.target.files?.[0])} />
    <div className="mx-auto w-full max-w-[1500px] px-4 py-5 md:px-7 md:py-7">
      <div className="grid gap-5 xl:grid-cols-[minmax(0,1.08fr)_minmax(430px,.72fr)]">
        <section className="hidden overflow-hidden rounded-[24px] border border-white/10 bg-[#080a15] shadow-2xl shadow-black/40 xl:block">
          <div className="relative min-h-[245px] overflow-hidden border-b border-white/10 p-7 md:p-10">
            <img src="/assets/tool-clone-voice.png" alt="Micrófono en estudio musical" className="absolute inset-0 h-full w-full object-cover opacity-45" />
            <div className="absolute inset-0 bg-gradient-to-r from-[#070914] via-[#070914]/90 to-[#070914]/20" />
            <div className="relative z-10 max-w-[600px]">
              <div className="flex flex-wrap items-center gap-3"><h1 className="bg-gradient-to-r from-fuchsia-500 to-pink-500 bg-clip-text text-4xl font-black tracking-tight text-transparent md:text-6xl">Video Karaoke</h1><span className="rounded-md bg-blue-600 px-2.5 py-1 text-[11px] font-black">NUEVO</span></div>
              <h2 className="mt-3 text-lg font-extrabold md:text-xl">Convierte tu canción en un video karaoke con letra sincronizada</h2>
              <p className="mt-2 max-w-xl text-sm leading-6 text-slate-300 md:text-base">Sube tu canción, sincronizamos la letra y te entregamos un video listo para cantar.</p>
            </div>
          </div>
          <div className="p-5 md:p-7">
            <h3 className="text-lg font-extrabold">Comienza tu karaoke</h3>
            <div className="mt-4 grid gap-4 md:grid-cols-2">
              <StartCard icon={Upload} title="Subir una canción" text="Sube un archivo de audio o video desde tu dispositivo." button="Seleccionar archivo" onClick={() => fileRef.current?.click()} />
              <StartCard icon={Music2} title="Elegir de mi Biblioteca" text="Usa una canción que ya generaste en LucIAna Music." button="Abrir Biblioteca" onClick={() => { setFileName('Luz de madrugada.mp3'); setHasAudio(true); }} secondary />
            </div>
            <div className="mt-4 grid gap-2 rounded-2xl border border-white/10 bg-white/[.02] p-3 sm:grid-cols-2 lg:grid-cols-4">
              <Feature icon={Upload} text="Sincronización inteligente de letras"/><Feature icon={Volume2} text="Elimina la voz o conserva coros"/><Feature icon={Image} text="Fondos y estilos personalizables"/><Feature icon={Video} text="Exporta en HD 720p / 1080p"/>
            </div>
            <p className="mt-4 text-[11px] text-slate-500">Vista previa visual. No se procesará ningún archivo ni se descontarán créditos.</p>
          </div>
        </section>

        <section className="flex min-h-[650px] flex-col overflow-hidden rounded-[24px] border border-white/10 bg-[#080a15] shadow-2xl shadow-black/40">
          <header className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div className="flex items-center gap-3"><ArrowLeft className="h-4 w-4 text-slate-400"/><strong>Nuevo Karaoke</strong></div><div className="flex items-center gap-2"><span className="rounded-full bg-white/5 px-3 py-1.5 text-xs font-bold">Créditos: {credits.toLocaleString('es-MX')}</span><HelpCircle className="h-5 w-5 text-slate-400"/></div></header>
          <div className="px-4 pt-5 md:px-6"><div className="relative grid grid-cols-5"><div className="absolute left-[10%] right-[10%] top-4 h-px bg-white/15"><div className="h-full bg-pink-500 transition-all" style={{width:`${Math.max(0,(step-1)*25)}%`}}/></div>{steps.map((label,i)=>{const n=i+1;return <button key={label} onClick={()=>setStep(n)} className="relative z-10 flex min-w-0 flex-col items-center gap-2"><span className={`grid h-8 w-8 place-items-center rounded-full border text-xs font-black ${n<=step?'border-pink-500 bg-pink-600':'border-white/20 bg-[#0b0d18] text-slate-400'}`}>{n<step?<Check className="h-4 w-4"/>:n}</span><small className={`w-full truncate text-center text-[9px] md:text-[10px] ${n===step?'text-pink-300':'text-slate-400'}`}>{label}</small></button>})}</div></div>
          <div className="flex-1 p-5 md:p-6">
            {step===1&&<AudioStep fileName={fileName} hasAudio={hasAudio} playing={playing} onPlay={()=>setPlaying(!playing)} onUpload={()=>fileRef.current?.click()} onLibrary={()=>{setFileName('Luz de madrugada.mp3');setHasAudio(true)}} onClear={()=>setHasAudio(false)}/>} 
            {step===2&&<LyricsStep mode={lyricsMode} setMode={setLyricsMode}/>} 
            {step===3&&<AudioSettings removeVoice={removeVoice} setRemoveVoice={setRemoveVoice} instrumentalVolume={instrumentalVolume} setInstrumentalVolume={setInstrumentalVolume} chorusVolume={chorusVolume} setChorusVolume={setChorusVolume} pitch={pitch} setPitch={setPitch} speed={speed} setSpeed={setSpeed}/>} 
            {step===4&&<DesignStep format={format} setFormat={setFormat} preset={preset} setPreset={setPreset} fontSize={fontSize} setFontSize={setFontSize} textColor={textColor} setTextColor={setTextColor} activeColor={activeColor} setActiveColor={setActiveColor} fontFamily={fontFamily} setFontFamily={setFontFamily} position={position} setPosition={setPosition} alignment={alignment} setAlignment={setAlignment}/>} {step===5&&<ExportStep fileName={fileName} format={format} preset={preset} instrumentalVolume={instrumentalVolume} chorusVolume={chorusVolume}/>} 
          </div>
          <footer className="sticky bottom-0 flex items-center justify-between gap-3 border-t border-white/10 bg-[#080a15]/95 p-4 backdrop-blur md:px-6"><button disabled={step===1} onClick={()=>setStep(step-1)} className="inline-flex h-11 items-center gap-2 rounded-xl border border-white/10 px-4 text-sm font-bold text-slate-300 disabled:opacity-30"><ArrowLeft className="h-4 w-4"/> Atrás</button>{step<5?<button onClick={()=>setStep(step+1)} className="inline-flex h-11 min-w-[165px] items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-fuchsia-600 to-pink-600 px-5 text-sm font-black">Continuar <ArrowRight className="h-4 w-4"/></button>:<button onClick={()=>setShowNotice(true)} className="h-11 rounded-xl bg-gradient-to-r from-fuchsia-600 to-pink-600 px-5 text-sm font-black">Generar Video Karaoke</button>}</footer>
        </section>
      </div>
    </div>
    {showNotice&&<div className="fixed inset-0 z-[400] grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl border border-pink-500/30 bg-[#0b0d18] p-6 text-center shadow-2xl shadow-pink-900/30"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-pink-500/10 text-pink-400"><Video className="h-7 w-7"/></span><h3 className="mt-4 text-xl font-black">Integración en preparación</h3><p className="mt-2 text-sm leading-6 text-slate-300">La generación real estará disponible cuando activemos la integración con Youka.</p><p className="mt-3 text-xs text-slate-500">No se descontaron créditos ni se procesó ningún archivo.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><button onClick={()=>setShowNotice(false)} className="h-11 rounded-xl border border-white/10 text-sm font-bold">Cerrar</button><button onClick={()=>{setShowNotice(false);setShowResult(true)}} className="h-11 rounded-xl bg-gradient-to-r from-fuchsia-600 to-pink-600 text-sm font-black">Ver resultado mock</button></div></div></div>}
  </div>;
}

function StartCard({icon:Icon,title,text,button,onClick,secondary=false}:any){return <article className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-xl bg-fuchsia-500/10 text-fuchsia-400"><Icon className="h-7 w-7"/></span><div><strong>{title}</strong><p className="mt-1 text-sm leading-5 text-slate-400">{text}</p><span className="mt-3 inline-block rounded-md bg-white/5 px-2 py-1 text-[10px] font-bold text-slate-300">MP3, WAV, M4A, MP4</span></div></div><button onClick={onClick} className={`mt-5 h-11 w-full rounded-xl text-sm font-extrabold ${secondary?'border border-white/10 bg-white/5':'bg-gradient-to-r from-fuchsia-600 to-pink-600'}`}>{button}</button></article>}
function Feature({icon:Icon,text}:any){return <div className="flex items-center gap-3 rounded-xl p-2.5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-pink-500/10 text-pink-400"><Icon className="h-5 w-5"/></span><span className="text-xs font-semibold leading-4 text-slate-200">{text}</span></div>}
function AudioStep({fileName,hasAudio,playing,onPlay,onUpload,onLibrary,onClear}:any){return <div><h3 className="font-extrabold">1. Selecciona tu canción</h3><div className="mt-4 grid grid-cols-2 rounded-xl bg-white/[.04] p-1"><button onClick={onUpload} className="rounded-lg border border-pink-500 py-2.5 text-xs font-bold text-pink-200">Subir canción</button><button onClick={onLibrary} className="rounded-lg py-2.5 text-xs font-bold text-slate-300">Mi Biblioteca</button></div>{hasAudio?<div className="mt-4 rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-pink-500/15 text-pink-400"><FileAudio/></span><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{fileName}</strong><small className="text-slate-400">03:58 · 9.2 MB</small></div><button onClick={onClear}><X className="h-4 w-4 text-slate-400"/></button></div><div className="mt-4 flex items-center gap-3"><button onClick={onPlay} className="grid h-10 w-10 place-items-center rounded-full border border-white/10">{playing?<Pause className="h-4 w-4"/>:<Play className="h-4 w-4"/>}</button><div className="h-8 flex-1 opacity-60 [background:repeating-linear-gradient(90deg,rgba(148,163,184,.55)_0_2px,transparent_2px_5px)]"/></div></div>:<button onClick={onUpload} className="mt-4 grid min-h-36 w-full place-items-center rounded-2xl border border-dashed border-pink-500/40 bg-pink-500/[.03]"><span><Upload className="mx-auto h-7 w-7 text-pink-400"/><strong className="mt-2 block text-sm">Seleccionar archivo</strong><small className="text-slate-500">MP3, WAV, M4A o MP4</small></span></button>}<h3 className="mt-6 font-extrabold">2. Información de la canción <span className="text-xs font-normal text-slate-500">(opcional)</span></h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Título" value="Si te vuelves a enamorar"/><Field label="Artista" value="Ruben Vidal"/></div><div className="mt-3 max-w-[210px]"><Field label="Género" value="Balada"/></div></div>}
function LyricsStep({mode,setMode}:any){const[analyzing,setAnalyzing]=useState(false);const[lyricsFile,setLyricsFile]=useState('');const file=useRef<HTMLInputElement>(null);const select=(id:string)=>{setMode(id);if(id==='auto'){setAnalyzing(true);window.setTimeout(()=>setAnalyzing(false),900)}};return <div><input ref={file} type="file" accept=".lrc,.txt" className="hidden" onChange={e=>setLyricsFile(e.target.files?.[0]?.name||'')}/><h3 className="font-extrabold">2. Letra de la canción</h3><div className="mt-4 grid grid-cols-3 rounded-xl bg-white/[.04] p-1">{[['auto','Detectar automáticamente'],['paste','Pegar letra'],['file','Subir archivo']].map(([id,label])=><button key={id} onClick={()=>{select(id);if(id==='file')file.current?.click()}} className={`rounded-lg px-2 py-2.5 text-[10px] font-bold ${mode===id?'border border-pink-500 text-pink-200':'text-slate-400'}`}>{label}</button>)}</div>{lyricsFile?<p className="mt-3 rounded-lg bg-white/5 p-2 text-xs text-slate-300">Archivo seleccionado: {lyricsFile}</p>:null}<div className="mt-4 grid min-h-[280px] gap-4 rounded-2xl border border-white/10 bg-white/[.02] p-4 md:grid-cols-[1fr_180px]"><textarea placeholder={mode==='paste'?'Pega aquí la letra completa de tu canción...':''} defaultValue={mode==='paste'?'':'[00:00.00]\nSi te vuelves a enamorar\n[00:08.20]\nNo te enamores de mí\n[00:15.40]\nPorque yo no sé amar'} className="min-h-52 resize-none bg-transparent text-xs leading-7 text-slate-300 outline-none"/><div className="grid place-items-center rounded-xl bg-purple-900/30 p-4 text-center"><div>{analyzing?<><span className="mx-auto block h-8 w-8 animate-spin rounded-full border-2 border-pink-500 border-t-transparent"/><strong className="mt-3 block">Analizando letra...</strong></>:<><Sparkles className="mx-auto h-6 w-6 text-pink-400"/><strong className="mt-2 block">Letra sincronizada</strong><span className="text-xl font-black text-pink-300">94%</span><small className="mt-2 block text-slate-400">Puedes editar los tiempos después.</small></>}</div></div></div></div>}
function AudioSettings({removeVoice,setRemoveVoice,instrumentalVolume,setInstrumentalVolume,chorusVolume,setChorusVolume,pitch,setPitch,speed,setSpeed}:any){return <div><h3 className="font-extrabold">3. Configura el audio del karaoke</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Choice active={removeVoice} onClick={()=>setRemoveVoice(true)} icon={Volume2} title="Eliminar voz principal" text="Remueve la voz principal."/><Choice active={!removeVoice} onClick={()=>setRemoveVoice(false)} icon={Mic2} title="Conservar coros" text="Mantiene los coros de fondo."/></div><Slider label="Volumen instrumental" value={`${instrumentalVolume}%`} valueNumber={instrumentalVolume} onChange={(e:any)=>setInstrumentalVolume(Number(e.target.value))}/><Slider label="Volumen de coros" value={`${chorusVolume}%`} valueNumber={chorusVolume} onChange={(e:any)=>setChorusVolume(Number(e.target.value))}/><Slider label="Tono" value={pitch>0?`+${pitch}`:String(pitch)} min={-12} max={12} valueNumber={pitch} onChange={(e:any)=>setPitch(Number(e.target.value))}/><Slider label="Velocidad" value={`${speed.toFixed(1)}×`} min={0.5} max={1.5} step={0.1} valueNumber={speed} onChange={(e:any)=>setSpeed(Number(e.target.value))}/><div className="mt-6 flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.025] p-3"><button className="grid h-10 w-10 place-items-center rounded-full bg-pink-600"><Play className="h-4 w-4"/></button><div className="h-7 flex-1 opacity-50 [background:repeating-linear-gradient(90deg,rgba(244,114,182,.75)_0_2px,transparent_2px_5px)]"/><small className="text-slate-400">00:18</small></div></div>}
function DesignStep({format,setFormat,preset,setPreset,fontSize,setFontSize,textColor,setTextColor,activeColor,setActiveColor,fontFamily,setFontFamily,position,setPosition,alignment,setAlignment}:any){const ratios:any={'16:9':'aspect-video','9:16':'aspect-[9/16]','1:1':'aspect-square'};const presets=['Clásico','Neon','Romántico','Noche','Rock','Elegante','Urbano'];return <div><h3 className="font-extrabold">4. Diseña tu Video Karaoke</h3><p className="mt-1 text-xs text-slate-400">Todos los cambios se reflejan al instante en la vista previa.</p><h4 className="mt-5 text-xs font-black uppercase tracking-wider text-slate-400">Formato</h4><div className="mt-2 grid grid-cols-3 gap-2">{['16:9','9:16','1:1'].map(item=><button key={item} onClick={()=>setFormat(item)} className={`rounded-xl border p-3 text-center ${format===item?'border-pink-500 bg-pink-500/10':'border-white/10'}`}><span className={`mx-auto block border border-current ${item==='16:9'?'h-6 w-11':item==='9:16'?'h-9 w-5':'h-7 w-7'}`}/><strong className="mt-2 block text-xs">{item}</strong></button>)}</div><h4 className="mt-5 text-xs font-black uppercase tracking-wider text-slate-400">Estilos Luciana</h4><div className="mt-2 flex flex-wrap gap-2">{presets.map(item=><button key={item} onClick={()=>setPreset(item)} className={`rounded-full border px-3 py-2 text-xs font-bold ${preset===item?'border-pink-500 bg-pink-500/10 text-pink-300':'border-white/10 text-slate-400'}`}>{item}</button>)}</div><div className="mt-5 grid gap-4 md:grid-cols-[180px_1fr]"><div className="space-y-3"><label className="block text-[11px] text-slate-400">Fuente<select value={fontFamily} onChange={e=>setFontFamily(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-white/10 bg-[#0b0d18] px-3 text-xs text-white"><option>Montserrat</option><option>Poppins</option><option>Inter</option></select></label><Slider label="Tamaño" value={`${fontSize}px`} valueNumber={fontSize} onChange={(e:any)=>setFontSize(Number(e.target.value))}/><Color label="Color de letra" value={textColor} onChange={setTextColor}/><Color label="Palabra activa" value={activeColor} onChange={setActiveColor}/><SelectField label="Posición" value={position} options={['Superior','Centro','Centro inferior']} onChange={setPosition}/><SelectField label="Alineación" value={alignment} options={['Izquierda','Centrada','Derecha']} onChange={setAlignment}/></div><Preview formatClass={ratios[format]} fontSize={fontSize} textColor={textColor} activeColor={activeColor} preset={preset} fontFamily={fontFamily} position={position} alignment={alignment}/></div></div>}
function ExportStep({fileName,format,preset,instrumentalVolume,chorusVolume}:any){return <div><h3 className="font-extrabold">5. Exporta tu Video Karaoke</h3><div className="mt-4 grid gap-4 md:grid-cols-[190px_1fr]"><div className="space-y-3"><Field label="Resolución" value="1080p"/><Summary label="Canción" value={fileName}/><Summary label="Duración" value="03:58"/><Summary label="Formato" value={format}/><Summary label="Diseño" value={preset}/><Summary label="Audio" value={`Instrumental ${instrumentalVolume}% · Coros ${chorusVolume}%`}/></div><Preview/></div><div className="mt-5 rounded-xl border border-white/10 bg-white/[.025] p-4"><small className="text-slate-400">Costo estimado</small><strong className="block text-xl">-- créditos</strong><p className="mt-1 text-xs text-slate-500">El costo final se calculará antes de generar el video.</p></div></div>}
function Preview({formatClass='aspect-video',fontSize=18,textColor='#ffffff',activeColor='#ff2f92',preset='Neon',fontFamily='Montserrat',position='Centro inferior',alignment='Centrada'}:any){const vertical=position==='Superior'?'top-10':position==='Centro'?'top-1/2 -translate-y-1/2':'bottom-8';const horizontal=alignment==='Izquierda'?'text-left':alignment==='Derecha'?'text-right':'text-center';return <div className={`mx-auto mt-5 w-full max-w-lg overflow-hidden rounded-2xl border border-white/10 bg-black ${formatClass}`}><div className="relative h-full min-h-48"><img src="/assets/cover-luz-madrugada.png" alt="Vista previa del karaoke" className="absolute inset-0 h-full w-full object-cover opacity-75"/><span className="absolute left-3 top-3 rounded-full bg-black/45 px-2 py-1 text-[9px] font-bold text-white">{preset}</span><div className={`absolute inset-x-3 ${vertical} ${horizontal} font-black leading-tight drop-shadow-lg`} style={{fontSize,color:textColor,fontFamily}}><span style={{color:activeColor}}>Si te vuelves</span> a enamorar<br/>No te enamores de mí</div><div className="absolute inset-x-0 bottom-0 h-1 bg-white/10"><div className="h-full w-2/5 bg-pink-500"/></div></div></div>}
function KaraokeResult({onAgain}:any){return <div className="h-full overflow-y-auto bg-[#050611] p-5 text-white md:p-10"><div className="mx-auto max-w-4xl rounded-[28px] border border-white/10 bg-[#080a15] p-5 text-center md:p-8"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-emerald-500/10 text-emerald-400"><Check className="h-8 w-8"/></span><h1 className="mt-5 text-3xl font-black">Tu Video Karaoke está listo</h1><p className="mt-2 text-sm text-slate-400">Vista previa del resultado que recibirás cuando activemos la generación.</p><div className="mx-auto mt-7 max-w-2xl"><Preview/></div><p className="mt-6 rounded-xl border border-white/10 bg-white/[.025] p-4 text-xs text-slate-400">Cuando activemos la generación, tu video estará disponible temporalmente para descargar.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><button disabled className="h-12 rounded-xl bg-white/5 text-sm font-bold text-slate-500">Descargar MP4</button><button onClick={onAgain} className="h-12 rounded-xl bg-gradient-to-r from-fuchsia-600 to-pink-600 text-sm font-black">Crear otro karaoke</button><button className="h-12 rounded-xl border border-white/10 text-sm font-bold">Volver a Biblioteca</button></div></div></div>}
function Summary({label,value}:any){return <div className="rounded-lg border border-white/10 bg-white/[.025] p-3"><small className="block text-slate-500">{label}</small><strong className="mt-1 block truncate text-xs">{value}</strong></div>}
function Color({label,value,onChange}:any){return <label className="flex items-center justify-between text-[11px] text-slate-400"><span>{label}</span><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-9 w-12 rounded border border-white/10 bg-transparent"/></label>}
function SelectField({label,value,options,onChange}:any){return <label className="block text-[11px] text-slate-400">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-white/10 bg-[#0b0d18] px-3 text-xs text-white">{options.map((option:string)=><option key={option}>{option}</option>)}</select></label>}
function Field({label,value}:any){return <label className="block text-[11px] text-slate-400">{label}<input defaultValue={value} className="mt-1 h-10 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-xs font-semibold text-white outline-none focus:border-pink-500"/></label>}
function Choice({active=false,onClick,icon:Icon,title,text}:any){return <button onClick={onClick} className={`flex gap-3 rounded-xl border p-4 text-left ${active?'border-pink-500 bg-pink-500/[.06]':'border-white/10 bg-white/[.025]'}`}><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${active?'bg-pink-500':'bg-white/5 text-slate-400'}`}>{active?<Check className="h-4 w-4"/>:<Icon className="h-4 w-4"/>}</span><span><strong className="block text-sm">{title}</strong><small className="text-slate-400">{text}</small></span></button>}
function Slider({label,value,defaultValue,valueNumber,onChange,min=0,max=100,step=1}:any){return <label className="mt-6 block"><span className="flex justify-between text-xs"><span>{label}</span><b>{value}</b></span><input type="range" min={min} max={max} step={step} {...(valueNumber===undefined?{defaultValue}:{value:valueNumber})} onChange={onChange} className="mt-3 w-full accent-pink-500"/></label>}
function Toggle({label}:any){const[on,setOn]=useState(false);return <button onClick={()=>setOn(!on)} className="flex w-full items-center justify-between text-xs text-slate-300"><span>{label}</span><span className={`h-5 w-9 rounded-full p-0.5 ${on?'bg-pink-500':'bg-white/10'}`}><span className={`block h-4 w-4 rounded-full bg-white transition-transform ${on?'translate-x-4':''}`}/></span></button>}
