-- TEMP-LOGGING: quitar despues de diagnostico
create table if not exists public.r2_copy_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  task_id text not null,
  user_id uuid null references auth.users(id) on delete set null,
  kind text not null,
  suno_audio_id text null,
  source_host text null,
  source_url text null,
  fetch_status integer null,
  download_ms integer null,
  size_bytes bigint null,
  content_type text null,
  fallback_used boolean not null default false,
  error_step text null,
  error_message text null
);

create index if not exists idx_r2_copy_logs_created_at
  on public.r2_copy_logs (created_at desc);

create index if not exists idx_r2_copy_logs_task_id
  on public.r2_copy_logs (task_id);

create index if not exists idx_r2_copy_logs_kind_created_at
  on public.r2_copy_logs (kind, created_at desc);
