-- Create song_likes table for storing user likes/favorites
CREATE TABLE IF NOT EXISTS public.song_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  song_id UUID NOT NULL,
  liked_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE(user_id, song_id)
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_song_likes_user_id ON public.song_likes(user_id);
CREATE INDEX IF NOT EXISTS idx_song_likes_song_id ON public.song_likes(song_id);
CREATE INDEX IF NOT EXISTS idx_song_likes_liked_at ON public.song_likes(liked_at DESC);

-- Enable Row Level Security
ALTER TABLE public.song_likes ENABLE ROW LEVEL SECURITY;

-- Create policies
-- Users can only see their own likes
CREATE POLICY "Users can view their own likes" ON public.song_likes
  FOR SELECT USING (auth.uid() = user_id);

-- Users can insert their own likes
CREATE POLICY "Users can insert their own likes" ON public.song_likes
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Users can delete their own likes
CREATE POLICY "Users can delete their own likes" ON public.song_likes
  FOR DELETE USING (auth.uid() = user_id);

-- Note: song_id references library_items.id but we don't add a foreign key constraint
-- because library_items might be in a different schema or have complex deletion rules